version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - corepack enable pnpm
      - cd link
      - pnpm install
      - cd ../ui
      - pnpm install
  build:
    on-failure: ABORT
    commands:
      - cd ../ui
      - pnpm build
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E3P9ENTEI8DLLN --paths '/*'
artifacts:
  files:
    - "**/*"
  secondary-artifacts:
    ui:
      base-directory: ui/dist
      files:
        - "**/*"
