version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - corepack enable pnpm
      - pnpm config set store-dir .pnpm-store
      - cd link
      - pnpm install
      - cd ../ui
      - pnpm install
  build:
    on-failure: ABORT
    commands:
      - cd ../ui
      - pnpm typecheck
      - pnpm test -- --watch false --reporter junit --outputFile test-report.xml
      - pnpm playwright install --with-deps chromium
      - NODE_OPTIONS=--max-old-space-size=3072 CI=true pnpm playwright test -c playwright-ct.config.ts
      - pnpm build
      - cd ../link
      - pnpm typecheck
      - pnpm db:generate
      - pnpm test:db:up
      - sleep 15
      - pnpm test -- --watch false --reporter junit --outputFile test-report.xml
      - pnpm build:node
  post_build:
    commands:
      - cd ../ui
      - aws s3 sync --delete dist s3://dabase-ui
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

artifacts:
  files:
    - "ui/test-ct-output/**"

reports:
  all:
    files:
      - "**/*-report.xml"
    file-format: "JUNITXML"
  link:
    files:
      - "link/test-report.xml"
    file-format: "JUNITXML"
  ui:
    files:
      - "ui/test-report.xml"
      - "ui/test-ct-report.xml"
    file-format: "JUNITXML"

cache:
  paths:
    - ".pnpm-store/**/*"
    - "/root/.cache/ms-playwright/**/*"
    - "ui/playwright/.cache/**/*"
