version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - sudo yum install libxcrypt-compat
      - corepack enable pnpm
      - cd link
      - pnpm install
      - cd ../ui
      - pnpm install
  # Use pre_build instead of build for building to avoid artifacts upload in case of failure
  # https://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases:~:text=The%20UPLOAD_ARTIFACTS%20phase%20is%20always%20attempted%2C%20even%20if%20the%20BUILD%20phase%20fails.
  pre_build:
    commands:
      - cd ../link
      - pnpm build:all
      - cd ../ui
      - pnpm build
      - cd ..
artifacts:
  files:
    - "**/*"
  secondary-artifacts:
    link:
      base-directory: link
      files:
        - "dist/*"
    ui:
      base-directory: ui
      files:
        - "dist/*"
