version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - corepack enable pnpm
      - cd link
      - pnpm install
      - cd ../ui
      - pnpm install
  build:
    on-failure: ABORT
    commands:
      - cd ../ui
      - pnpm typecheck
      - pnpm build
      - cd ../link
      - pnpm typecheck
      - pnpm build:node
      - pnpm db:generate
      - docker-compose -f docker-compose.yml -p dabase-link-dev --env-file .env.development up & (sleep 30 && pnpm test -- --watch false)
  post_build:
    commands:
      - cd ../ui
      - aws s3 sync --delete dist s3://dabase-ui
      - aws cloudfront create-invalidation --distribution-id E3P9ENTEI8DLLN --paths '/*'

reports:
  link:
    files:
      - "link/test-report.xml"
    discard-paths: no
