version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm i -g corepack@latest
      - corepack enable pnpm
      - pnpm config set store-dir .pnpm-store
      - cd shared
      - pnpm install
      - cd ../cloud
      - pnpm install
      - cd ../link
      - pnpm install
      - cd ../ui
      - pnpm install
      - cd ../about
      - pnpm install
  build:
    on-failure: ABORT
    commands:
      - cd ../cloud
      - pnpm prisma generate
      - pnpm typecheck
      - pnpm build
      - rm -rf node_modules
      - mkdir node_modules # Keep empty node_modules to prevent EB from installing deps
      - zip -r application.zip package.json node_modules dist
      - pnpm install # Reinstall deps for later steps

      - cd ../ui
      - pnpm typecheck
      - pnpm test -- --watch false --reporter junit --outputFile test-report.xml
      # - pnpm playwright install --with-deps chromium
      # - NODE_OPTIONS=--max-old-space-size=3072 CI=true pnpm playwright test -c playwright-ct.config.ts
      - pnpm build

      - cd ../about
      - pnpm typecheck
      - pnpm build

      - cd ../link
      - pnpm typecheck
      - pnpm db:generate
      - pnpm test:db:up
      - sleep 15
      - pnpm test -- --watch false --reporter junit --outputFile test-report.xml
      - pnpm build:node
  post_build:
    commands:
      - cd ../cloudFormation
      - aws s3 sync . s3://dabase-cloudformation --delete
      - >
        aws cloudformation deploy \
          --stack-name dabase-2025-01-18-19-40-48 \
          --template-file main.yml \
          --capabilities CAPABILITY_NAMED_IAM

      - cd ../cloud

      # Run migrations
      - |
        urlencode() {
          local length="${#1}"
          for (( i = 0; i < length; i++ )); do
            local c="${1:i:1}"
            case $c in
              [a-zA-Z0-9.~_-]) printf "$c" ;;
              *) printf '%%%02X' "'$c"
            esac
          done
        }
      - export DB_SECRET=$(aws secretsmanager get-secret-value --secret-id $DABASE_CLOUD_DB_SECRET_ARN --query SecretString --output text)
      - export DABASE_CLOUD_DB_PASSWORD=$(echo $DB_SECRET | jq -r '.password')
      - export DABASE_CLOUD_DB_USERNAME=$(echo $DB_SECRET | jq -r '.username')
      - export DATABASE_URL="postgresql://${DABASE_CLOUD_DB_USERNAME}:$(urlencode $DABASE_CLOUD_DB_PASSWORD)@${DABASE_CLOUD_DB_ENDPOINT}/dabase_cloud?schema=public"
      - echo $DATABASE_URL
      - pnpm prisma migrate deploy

      # Deploy server
      - aws s3 cp application.zip s3://dabase-cloud-source/$CODEBUILD_BUILD_NUMBER.zip
      - >
        aws elasticbeanstalk create-application-version \
          --application-name dabase-cloud \
          --version-label $CODEBUILD_BUILD_NUMBER \
          --source-bundle S3Bucket=dabase-cloud-source,S3Key=$CODEBUILD_BUILD_NUMBER.zip
      - >
        aws elasticbeanstalk update-environment \
          --environment-name dabase-cloud \
          --version-label $CODEBUILD_BUILD_NUMBER

      - >
        aws elasticbeanstalk wait environment-updated \
          --environment-name dabase-cloud \
          --version-label $CODEBUILD_BUILD_NUMBER

      - cd ../ui
      - aws s3 sync dist s3://dabase-ui
      - aws cloudfront create-invalidation --distribution-id $DABASE_UI_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

      - cd ../about
      - aws s3 sync out s3://dabase-about
      - aws cloudfront create-invalidation --distribution-id $DABASE_ABOUT_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

reports:
  link:
    files:
      - "link/test-report.xml"
    file-format: "JUNITXML"
  ui:
    files:
      - "ui/test-report.xml"
    file-format: "JUNITXML"
  # ui-ct:
  #   files:
  #     - "ui/test-ct-report.xml"
  #   file-format: "JUNITXML"

cache:
  paths:
    - "/root/**/.pnpm-store/**/*"
    - "/root/.cache/ms-playwright/**/*"
