version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - corepack enable pnpm
      - cd link
      - pnpm install
      - cd ../ui
      - pnpm install
  build:
    commands:
      # - cd ../link
      # - pnpm build:all
      - cd ../ui
      - pnpm build
      - cd ..
artifacts:
  files:
    - "**/*"
  secondary-artifacts:
    link:
      base-directory: link
      files:
        - "dist/*"
    ui:
      base-directory: ui
      files:
        - "dist/*"
