version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - corepack enable pnpm
      - cd link
      - pnpm install
      - cd ../ui
      - pnpm install
  build:
    on-failure: ABORT
    commands:
      - cd ../ui
      - pnpm typecheck
      - pnpm build
      - cd ../link
      - pnpm typecheck
      - pnpm build:node
      - pnpm test:db:up
      - echo "Testing PostgreSQL connection..."
      - pg_isready -h localhost -p 5434 -U postgres
      - echo "Testing MySQL connection..."
      - mysqladmin ping -h localhost -P 3308 -u root -ppassword
      - pnpm test -- --watch false
  post_build:
    commands:
      - cd ../ui
      - aws s3 sync --delete dist s3://dabase-ui
      - aws cloudfront create-invalidation --distribution-id E3P9ENTEI8DLLN --paths '/*'

reports:
  link:
    files:
      - "link/test-report.xml"
    discard-paths: no
