version: 0.2

env:
  variables:
    CI: true

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - export IS_ABOUT_UNCHANGED=0
      - export IS_CLOUD_UNCHANGED=0
      - export IS_CLOUD_FORMATION_UNCHANGED=0
      - export IS_LINK_UNCHANGED=0
      - export IS_SHARED_UNCHANGED=0
      - export IS_UI_UNCHANGED=0

      # Find last successful build
      - |
        set -e  # Exit immediately if any command fails
        export MAX_ITEMS=100
        export BUILD_IDS=$(aws codebuild list-builds-for-project --project-name smartquery --sort-order DESCENDING --max-items $MAX_ITEMS)
        export INDEX=0
        while [ $INDEX -lt $MAX_ITEMS ]; do
          export CURRENT_BUILD_ID=$(echo $BUILD_IDS | jq -r --arg index $INDEX '.ids[$index | tonumber]')
          
          # Check if CURRENT_BUILD_ID is null (no more builds available)
          if [ "$CURRENT_BUILD_ID" = "null" ] || [ -z "$CURRENT_BUILD_ID" ]; then
            echo "No more builds available at index $INDEX"
            break
          fi
          
          export CURRENT_BUILD=$(aws codebuild batch-get-builds --ids $CURRENT_BUILD_ID)
          export CURRENT_BUILD_SUCCEEDED=$(echo $CURRENT_BUILD | jq -r '.builds[0].buildStatus')
          echo "Current build: $CURRENT_BUILD_ID, Succeeded: $CURRENT_BUILD_SUCCEEDED"

          if [ "$CURRENT_BUILD_ID" != "$CODEBUILD_BUILD_ID" ] && [ "$CURRENT_BUILD_SUCCEEDED" = "SUCCEEDED" ]; then
            echo "Last successful build: $CURRENT_BUILD_ID"
            export LAST_SUCCESSFUL_BUILD_SOURCE=$(echo $CURRENT_BUILD | jq -r '.builds[0].sourceVersion')
            export LAST_SUCCESSFUL_BUILD_SOURCE=$(echo $LAST_SUCCESSFUL_BUILD_SOURCE | sed 's|arn:aws:s3:::||')
            export LAST_SUCCESSFUL_BUILD_SOURCE="s3://$LAST_SUCCESSFUL_BUILD_SOURCE"
            break
          fi
          export INDEX=$((INDEX + 1))
        done

      - |
        set -e  # Exit immediately if any command fails
        if [ -z "$LAST_SUCCESSFUL_BUILD_SOURCE" ]; then
          echo "No previous successful build found. Building all packages."
        else
          aws s3 cp $LAST_SUCCESSFUL_BUILD_SOURCE last_source.zip
          rm -rf last_source
          unzip last_source.zip -d last_source

          if diff -r last_source/about about >/dev/null 2>&1; then
            export IS_ABOUT_UNCHANGED=1
          fi
          
          if diff -r last_source/cloud cloud >/dev/null 2>&1; then
            export IS_CLOUD_UNCHANGED=1
          fi
          
          if diff -r last_source/cloudFormation cloudFormation >/dev/null 2>&1; then
            export IS_CLOUD_FORMATION_UNCHANGED=1
          fi
          
          if diff -r last_source/link link >/dev/null 2>&1; then
            export IS_LINK_UNCHANGED=1
          fi
          
          if diff -r last_source/shared shared >/dev/null 2>&1; then
            export IS_SHARED_UNCHANGED=1
          fi
          
          if diff -r last_source/ui ui >/dev/null 2>&1; then
            export IS_UI_UNCHANGED=1
          fi
        fi

      - |
        echo "IS_ABOUT_UNCHANGED: $IS_ABOUT_UNCHANGED"
        echo "IS_CLOUD_UNCHANGED: $IS_CLOUD_UNCHANGED"
        echo "IS_CLOUD_FORMATION_UNCHANGED: $IS_CLOUD_FORMATION_UNCHANGED"
        echo "IS_LINK_UNCHANGED: $IS_LINK_UNCHANGED"
        echo "IS_SHARED_UNCHANGED: $IS_SHARED_UNCHANGED"
        echo "IS_UI_UNCHANGED: $IS_UI_UNCHANGED"

      - |
        export SKIP_ABOUT=$(($IS_ABOUT_UNCHANGED * $IS_CLOUD_FORMATION_UNCHANGED * $IS_SHARED_UNCHANGED))
        export SKIP_CLOUD=$(($IS_CLOUD_UNCHANGED * $IS_CLOUD_FORMATION_UNCHANGED * $IS_SHARED_UNCHANGED))
        export SKIP_CLOUD_FORMATION=$(($IS_CLOUD_FORMATION_UNCHANGED))
        export SKIP_LINK=$(($IS_LINK_UNCHANGED * $IS_SHARED_UNCHANGED))
        export SKIP_SHARED=$(($IS_ABOUT_UNCHANGED * $IS_CLOUD_UNCHANGED * $IS_CLOUD_FORMATION_UNCHANGED * $IS_LINK_UNCHANGED * $IS_UI_UNCHANGED))
        export SKIP_UI=$(($IS_UI_UNCHANGED * $IS_CLOUD_UNCHANGED * $IS_CLOUD_FORMATION_UNCHANGED * $IS_LINK_UNCHANGED * $IS_SHARED_UNCHANGED))

      - |
        echo "SKIP_ABOUT: $SKIP_ABOUT"
        echo "SKIP_CLOUD: $SKIP_CLOUD"
        echo "SKIP_CLOUD_FORMATION: $SKIP_CLOUD_FORMATION"
        echo "SKIP_LINK: $SKIP_LINK"
        echo "SKIP_SHARED: $SKIP_SHARED"
        echo "SKIP_UI: $SKIP_UI"

      - rm -rf last_source last_source.zip

      - npm i -g corepack@latest
      - corepack enable pnpm
      - pip install awsebcli

      - cd shared # Always navigate to shared to enable upcoming cd ../
      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_SHARED -eq 1 ]; then
          echo "Shared package is unchanged. Skipping install."
        else
          pnpm install
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_ABOUT -eq 1 ]; then
          echo "About package is unchanged. Skipping install."
        else
          cd ../about
          pnpm install
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_CLOUD -eq 1 ]; then
          echo "Cloud package is unchanged. Skipping install."
        else
          cd ../cloud
          pnpm install
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_LINK -eq 1 ]; then
          echo "Link package is unchanged. Skipping install."
        else
          cd ../link
          pnpm install
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_UI -eq 1 ]; then
          echo "UI package is unchanged. Skipping install."
        else
          cd ../ui
          pnpm install
        fi

  build:
    commands:
      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_SHARED -eq 1 ]; then
          echo "Shared package is unchanged. Skipping checks."
        else
          cd ../shared
          pnpm typecheck
          pnpm lint
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_ABOUT -eq 1 ]; then
          echo "About package is unchanged. Skipping build."
        else
          cd ../about
          pnpm typecheck
          pnpm lint
          pnpm build
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_CLOUD -eq 1 ]; then
          echo "Cloud package is unchanged. Skipping build."
        else
          cd ../cloud
          pnpm typecheck
          pnpm lint
          pnpm build
          mv node_modules node_modules_backup
          mkdir node_modules # Keep empty node_modules to prevent EB from installing deps
          zip -r application.zip .ebextensions .env.production dist node_modules package.json prisma/generated prisma/schema.prisma Procfile scripts
          rm -rf node_modules
          mv node_modules_backup node_modules
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_LINK -eq 1 ]; then
          echo "Link package is unchanged. Skipping build."

          # Add empty test results to prevent artifacts upload failure
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites/>" > ../link/test-report.xml
        else
          cd ../link
          pnpm typecheck
          pnpm lint
          pnpm db:up:test
          sleep 15
          pnpm test -- --watch false --reporter junit --outputFile test-report.xml
          pnpm db:down:test
          pnpm build:node
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_UI -eq 1 ]; then
          echo "UI package is unchanged. Skipping build."

          # Add empty test results to prevent artifacts upload failure
          mkdir ../ui/test-results
          touch ../ui/test-results/empty

          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites/>" > ../ui/test-ct-report.xml
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites/>" > ../ui/test-report.xml
        else
          # Initialize cloud types, they are needed for UI build because of the tRPC router import
          if [ $SKIP_CLOUD -eq 1 ]; then
            cd ../cloud
            pnpm install
            pnpm prisma generate
          fi

          # Initialize link types, they are needed for UI build because of the tRPC router import
          if [ $SKIP_LINK -eq 1 ]; then
            cd ../link
            pnpm install
          fi

          cd ../ui
          export VITE_UI_VERSION=$(echo -n $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
          echo VITE_UI_VERSION=$VITE_UI_VERSION >> .env
          echo -n $VITE_UI_VERSION > public/version
          pnpm typecheck
          pnpm lint
          pnpm test -- --watch false --reporter junit --outputFile test-report.xml
          pnpm playwright install --with-deps chromium
          NODE_OPTIONS='--max-old-space-size=8192' pnpm playwright test -c playwright-ct.config.ts
          pnpm build
          
          # Move all .js.map files to dist/sourcemaps/VITE_UI_VERSION/ for AWS RUM error tracking
          mkdir -p dist/sourcemaps/$VITE_UI_VERSION
          find dist -name "*.js.map" -type f -exec mv {} dist/sourcemaps/$VITE_UI_VERSION/ \;
        fi
  post_build:
    commands:
      # Skip deployment if previous phase failed, continue to next phase to upload test artifacts
      - |
        set -e  # Exit immediately if any command fails
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          echo "Build failed, skipping deployment"
          exit 1
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_ABOUT -eq 1 ]; then
          echo "About package is unchanged. Skipping deployment."
        else
          cd ../about
          aws s3 sync out s3://smartquery-about
          aws cloudfront create-invalidation --distribution-id $SMARTQUERY_ABOUT_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_CLOUD_FORMATION -eq 1 ]; then
          echo "CloudFormation package is unchanged. Skipping deployment."
        else
          cd ../cloudFormation
          ./deploy.sh
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_CLOUD -eq 1 ]; then
          echo "Cloud package is unchanged. Skipping deployment."
        else
          cd ../cloud

          # Run migrations
          export SMARTQUERY_CLOUD_DB_SECRET=$(aws secretsmanager get-secret-value --secret-id $SMARTQUERY_CLOUD_DB_SECRET_ARN --query SecretString --output text)
          chmod +x ./scripts/build-database-url.sh
          export DATABASE_URL=$(./scripts/build-database-url.sh)
          pnpm prisma migrate deploy

          # Deploy server
          aws s3 cp application.zip s3://smartquery-cloud-source/$CODEBUILD_BUILD_NUMBER.zip
          aws elasticbeanstalk create-application-version \
            --application-name smartquery-cloud \
            --version-label $CODEBUILD_BUILD_NUMBER \
            --source-bundle S3Bucket=smartquery-cloud-source,S3Key=$CODEBUILD_BUILD_NUMBER.zip
          
          # Use EB CLI to deploy (automatically waits for success and preserves environment config)
          eb deploy smartquery-cloud --version $CODEBUILD_BUILD_NUMBER
        fi

      - |
        set -e  # Exit immediately if any command fails
        if [ $SKIP_UI -eq 1 ]; then
          echo "UI package is unchanged. Skipping deployment."
        else
          cd ../ui
          aws s3 sync dist s3://smartquery-ui
          aws s3 cp s3://smartquery-ui/version s3://smartquery-ui/version --content-type text/plain
          aws cloudfront create-invalidation --distribution-id $SMARTQUERY_UI_CLOUDFRONT_DISTRIBUTION_ID --paths '/*'
        fi

reports:
  link:
    files:
      - "link/test-report.xml"
    file-format: "JUNITXML"
  ui:
    files:
      - "ui/test-report.xml"
    file-format: "JUNITXML"
  ui-ct:
    files:
      - "ui/test-ct-report.xml"
    file-format: "JUNITXML"

artifacts:
  files:
    # Playwright screenshots
    - 'ui/test-results/**/*'
  name: $CODEBUILD_BUILD_NUMBER/test-results
