services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql_db
    ports:
      - "5433:5432"
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
