AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion host for secure RDS access'

# To test SSH connectivity:
# ssh -i ~/.ssh/smartquery-bastion-key.pem ec2-user@bastion.smartquery.dev

Resources:
  BastionKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: smartquery-bastion-key2
      KeyType: ed25519

  BastionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BastionRole

  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-092ff8e60e2d51e19  # Amazon Linux 2023 AMI
      InstanceType: t3.nano
      KeyName: !Ref BastionKeyPair
      SubnetId: !ImportValue SmartqueryCloudPublicSubnet1
      SecurityGroupIds:
        - !ImportValue SmartqueryCloudBastionSecurityGroup
      IamInstanceProfile: !Ref BastionInstanceProfile

  BastionElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  BastionEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt BastionElasticIP.AllocationId
      InstanceId: !Ref BastionHost

Outputs:
  BastionPublicIP:
    Description: Public IP address of the bastion host
    Value: !Ref BastionElasticIP
    Export:
      Name: SmartqueryCloudBastionPublicIP
