Resources:
  CodeBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: "CODEPIPELINE"
      Environment:
        ComputeType: "BUILD_GENERAL1_LARGE"
        EnvironmentVariables:
          - Name: "SMARTQUERY_UI_CLOUDFRONT_DISTRIBUTION_ID"
            Value: !ImportValue CloudFrontDistributionUi
          - Name: "SMARTQUERY_ABOUT_CLOUDFRONT_DISTRIBUTION_ID"
            Value: !ImportValue CloudFrontDistributionAbout
          - Name: "SMARTQUERY_CLOUD_DB_SECRET_ARN"
            Value: !ImportValue CloudDbSecretArn
        Image: "aws/codebuild/standard:7.0"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
      Name: "smartquery"
      ServiceRole: !ImportValue IamRoleCodeBuildArn
      Source:
        Type: "CODEPIPELINE"
      VpcConfig:
        VpcId: !ImportValue CloudVpcId
        Subnets: !Split [',', !ImportValue CloudPrivateSubnets]
        SecurityGroupIds:
          - !ImportValue CloudCodeBuildSecurityGroup

Outputs:
  CodeBuild:
    Value: !Ref CodeBuild
    Export:
      Name: CodeBuild
