Resources:
  CodeBuildDabase:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: "CODEPIPELINE"
      Cache:
        Location: !ImportValue S3BucketCodeBuildCache
        Type: "S3"
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        EnvironmentVariables:
          - Name: "DABASE_UI_CLOUDFRONT_DISTRIBUTION_ID"
            Value: !ImportValue CloudFrontDistributionDabaseUi
          - Name: "DABASE_ABOUT_CLOUDFRONT_DISTRIBUTION_ID"
            Value: !ImportValue CloudFrontDistributionDabaseAbout
          - Name: "DABASE_CLOUD_DB_SECRET_ARN"
            Value: !ImportValue DabaseCloudDbSecretArn
          - Name: "DABASE_CLOUD_DB_ENDPOINT"
            Value: !ImportValue DabaseCloudDbEndpoint
        Image: "aws/codebuild/standard:7.0"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
      Name: "dabase"
      ServiceRole: !ImportValue IamRoleCodeBuildArn
      Source:
        Type: "CODEPIPELINE"
      VpcConfig:
        VpcId: !ImportValue DabaseCloudVpcId
        Subnets: !Split [',', !ImportValue DabaseCloudPrivateSubnets]
        SecurityGroupIds:
          - !ImportValue DabaseCloudCodeBuildSecurityGroup

Outputs:
  CodeBuildDabase:
    Value: !Ref CodeBuildDabase
    Export:
      Name: CodeBuildDabase
