Resources:
  CodeBuildSmartquery:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: "CODEPIPELINE"
      Environment:
        ComputeType: "BUILD_GENERAL1_LARGE"
        EnvironmentVariables:
          - Name: "SMARTQUERY_UI_CLOUDFRONT_DISTRIBUTION_ID"
            Value: !ImportValue CloudFrontDistributionSmartqueryUi
          - Name: "SMARTQUERY_ABOUT_CLOUDFRONT_DISTRIBUTION_ID"
            Value: !ImportValue CloudFrontDistributionSmartqueryAbout
          - Name: "SMARTQUERY_CLOUD_DB_SECRET_ARN"
            Value: !ImportValue SmartqueryCloudDbSecretArn
        Image: "aws/codebuild/standard:7.0"
        PrivilegedMode: true
        Type: "LINUX_CONTAINER"
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
      Name: "smartquery"
      ServiceRole: !ImportValue IamRoleCodeBuildArn
      Source:
        Type: "CODEPIPELINE"
      VpcConfig:
        VpcId: !ImportValue SmartqueryCloudVpcId
        Subnets: !Split [',', !ImportValue SmartqueryCloudPrivateSubnets]
        SecurityGroupIds:
          - !ImportValue SmartqueryCloudCodeBuildSecurityGroup

Outputs:
  CodeBuildSmartquery:
    Value: !Ref CodeBuildSmartquery
    Export:
      Name: CodeBuildSmartquery
