Resources:
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: "GitHubConnection"
      ProviderType: GitHub

Outputs:
  CodeStarConnectionArn:
    Value: !Ref CodeStarConnection
    Export:
      Name: CodeStarConnectionArn
