AWSTemplateFormatVersion: '2010-09-09'
Description: 'Elastic Beanstalk environment for Node.js application'

Resources:
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: dabase-cloud
      Description: 'Dabase Cloud'

  ElasticBeanstalkIamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: dabase-cloud-instance-profile
      Path: /
      Roles:
        - !Ref ElasticBeanstalkIamRole

  ElasticBeanstalkIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        # - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
      Policies:
        - PolicyName: RdsSecretAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue DabaseCloudDbSecretArn

  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn: ElasticBeanstalkApplication
    Properties:
      ApplicationName: dabase-cloud
      EnvironmentName: dabase-cloud
      SolutionStackName: '64bit Amazon Linux 2023 v6.5.2 running Node.js 22'
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: t2.micro
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !ImportValue DabaseCloudElasticBeanstalkSecurityGroup
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref ElasticBeanstalkIamInstanceProfile
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: 1
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: 1
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !ImportValue DabaseCloudVpcId
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !ImportValue DabaseCloudPrivateSubnets
        - Namespace: aws:elasticbeanstalk:application:environmentsecrets
          OptionName: DABASE_CLOUD_DB_SECRET
          Value: !ImportValue DabaseCloudDbSecretArn
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: DABASE_CLOUD_DB_ENDPOINT
          Value: !ImportValue DabaseCloudDbEndpoint
        - Namespace: aws:elasticbeanstalk:cloudwatch:logs
          OptionName: StreamLogs
          Value: true
        - Namespace: aws:elbv2:listener:443
          OptionName: ListenerEnabled
          Value: true
        - Namespace: aws:elbv2:listener:443
          OptionName: Protocol
          Value: HTTPS
        - Namespace: aws:elbv2:listener:443
          OptionName: SSLCertificateArns
          Value: 'arn:aws:acm:us-east-1:339712876040:certificate/5cfade6c-317f-4aff-974a-84d51650aca1'
        - Namespace: aws:elbv2:listener:default
          OptionName: ListenerEnabled
          Value: false
        - Namespace: aws:elasticbeanstalk:application
          OptionName: 'Application Healthcheck URL'
          Value: HTTPS:443/health

Outputs:
  ElasticBeanstalkEnvironmentEndpointUrl:
    Description: "Elastic Beanstalk Environment Endpoint URL"
    Value: !GetAtt ElasticBeanstalkEnvironment.EndpointURL
    Export:
      Name: DabaseCloudElasticBeanstalkEndpointUrl
