Resources:
  IamRoleCodeBuild:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
  
  IamRoleCodePipeline:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      Policies:
        - PolicyName: CodeStarConnectionAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "codepipeline.amazonaws.com"

Outputs:
  IamRoleCodeBuildArn:
    Value: !GetAtt IamRoleCodeBuild.Arn
    Export:
      Name: IamRoleCodeBuildArn
  
  IamRoleCodePipelineArn:
    Value: !GetAtt IamRoleCodePipeline.Arn
    Export:
      Name: IamRoleCodePipelineArn
