Resources:
  CloudFrontStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/cloudFront.yml"

  CodeBuildStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/codeBuild.yml"
    DependsOn:
      - CloudFrontStack
      - IamStack
      - RDSStack

  CodePipelineStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/codePipeline.yml"
    DependsOn:
      - CodeBuildStack
      - CodeStarConnectionsStack
      - IamStack
      - S3Stack

  CodeStarConnectionsStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/codeStarConnections.yml"

  CognitoStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/cognito.yml"

  ElasticBeanstalkSecurityGroupStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/elasticBeanstalkSecurityGroup.yml"
    DependsOn: VPCStack

  ElasticBeanstalkStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/elasticBeanstalk.yml"
    DependsOn:
      - ElasticBeanstalkSecurityGroupStack
      - RDSStack
      - VPCStack

  IamStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/iam.yml"
    DependsOn:
      - CloudFrontStack
      - S3Stack

  PinpointStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/pinpoint.yml"

  RDSStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/rds.yml"
    DependsOn:
      - ElasticBeanstalkSecurityGroupStack
      - VPCStack

  Route53Stack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/route53.yml"
    DependsOn:
      - CloudFrontStack
      - ElasticBeanstalkStack

  S3Stack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/s3.yml"

  VPCStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://dabase-cloudformation.s3.eu-central-1.amazonaws.com/vpc.yml"
