Resources:
  CloudFrontStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/cloudFront.yml"

  CodeBuildStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/codeBuild.yml"
    DependsOn:
      - CloudFrontStack
      - IamStack

  CodePipelineStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/codePipeline.yml"
    DependsOn:
      - CodeBuildStack
      - CodeStarConnectionsStack
      - IamStack
      - S3Stack

  CodeStarConnectionsStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/codeStarConnections.yml"

  CognitoStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/cognito.yml"

  Route53Stack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/route53.yml"
    DependsOn:
      - CloudFrontStack

  RUMStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/rum.yml"
    DependsOn:
      - CognitoStack

  S3Stack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/s3.yml"

  SESStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/ses.yml"

  IamStack:
    Type: "AWS::CloudFormation::Stack"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      TemplateURL: "https://smartquery-cloudformation.s3.eu-central-1.amazonaws.com/iam.yml"
    DependsOn:
      - CloudFrontStack
      - S3Stack
