Resources:
  Route53HostedZoneDabase:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "dabase.dev."

  Route53RecordSetDabaseUi:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseUiDomainName

  Route53RecordSetDabaseAboout:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "about.dabase.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseAboutDomainName

  Route53RecordSetDabaseCloud:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "cloud.dabase.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z215JYRZR1TBD5"  # Fixed hosted zone ID for Elastic Beanstalk in eu-central-1
        DNSName: !ImportValue DabaseCloudElasticBeanstalkEndpointUrl

  Route53RecordSetBastion:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "bastion.dabase.dev."
      Type: "A"
      TTL: "300"
      ResourceRecords:
        - !ImportValue DabaseCloudBastionPublicIP

  Route53RecordSetSesDkim1:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: !ImportValue DkimDNSTokenName1
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue1

  Route53RecordSetSesDkim2:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: !ImportValue DkimDNSTokenName2
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue2

  Route53RecordSetSesDkim3:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: !ImportValue DkimDNSTokenName3
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue3

  Route53RecordSetDmarc:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "_dmarc.dabase.dev."
      Type: "TXT"
      TTL: "3600"
      ResourceRecords:
        - '"v=DMARC1; p=reject; rua=mailto:dmarc@dabase.dev"'

  Route53RecordSetSpaceshipMx:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "MX"
      TTL: "3600"
      ResourceRecords:
        - "0 mx1.efwd.spaceship.net."
        - "0 mx2.efwd.spaceship.net."

  Route53RecordSetSpaceshipSpf:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "TXT"
      TTL: "3600"
      ResourceRecords:
        - '"v=spf1 include:spf.efwd.spaceship.net ~all"'

