Resources:
  Route53HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "smartquery.dev."

  Route53RecordSetUi:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "smartquery.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseUiDomainName

  Route53RecordSetAbout:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "about.smartquery.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseAboutDomainName

  Route53RecordSetCloud:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "cloud.smartquery.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z215JYRZR1TBD5"  # Fixed hosted zone ID for Elastic Beanstalk in eu-central-1
        DNSName: !ImportValue DabaseCloudElasticBeanstalkEndpointUrl

  Route53RecordSetBastion:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "bastion.smartquery.dev."
      Type: "A"
      TTL: "300"
      ResourceRecords:
        - !ImportValue DabaseCloudBastionPublicIP

  Route53RecordSetSesDkim1:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: !ImportValue DkimDNSTokenName1
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue1

  Route53RecordSetSesDkim2:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: !ImportValue DkimDNSTokenName2
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue2

  Route53RecordSetSesDkim3:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: !ImportValue DkimDNSTokenName3
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue3

  Route53RecordSetDmarc:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "_dmarc.smartquery.dev."
      Type: "TXT"
      TTL: "3600"
      ResourceRecords:
        - '"v=DMARC1; p=reject; rua=mailto:dmarc@smartquery.dev"'

  Route53RecordSetSpaceshipMx:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "smartquery.dev."
      Type: "MX"
      TTL: "3600"
      ResourceRecords:
        - "0 mx1.efwd.spaceship.net."
        - "0 mx2.efwd.spaceship.net."

  Route53RecordSetSpaceshipSpfAndStripeVerification:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "smartquery.dev."
      Type: "TXT"
      TTL: "3600"
      ResourceRecords:
        - '"stripe-verification=b675f45f2d01cd1774e0f4278720e194cb3f270ee7f382b09baecaf7a405741c"'
        - '"stripe-verification=f8137c32c9086ff8c31fa71aa54425f4a8291f0a91cc1efac15b3cb7e890a029"'
        - '"v=spf1 include:spf.efwd.spaceship.net ~all"'

  Route53RecordSetStripeDkimNew1:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "jkivbbrtb6n7ktnnx2n6lolfh3jehtuo._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "jkivbbrtb6n7ktnnx2n6lolfh3jehtuo.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkimNew2:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "z5vl5lyvm6ubguanfyeuvotu63lhysgj._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "z5vl5lyvm6ubguanfyeuvotu63lhysgj.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkimNew3:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "3zqxh27hsrlgufndjhodik72hj57gzca._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "3zqxh27hsrlgufndjhodik72hj57gzca.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkimNew4:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "7kxcki7spcgclvxxgewgtjg5uj2as4o2._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "7kxcki7spcgclvxxgewgtjg5uj2as4o2.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkimNew5:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "keabwkkdfsqmh2cd7vlxwflwpb4jv7vg._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "keabwkkdfsqmh2cd7vlxwflwpb4jv7vg.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkimNew6:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "wvou2wuz3aul35szabjblcj4hhzv6af3._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "wvou2wuz3aul35szabjblcj4hhzv6af3.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeBounce:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZone
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "bounce.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "custom-email-domain.stripe.com."

  # Old domain hosted zone for redirects
  Route53HostedZoneDabaseOld:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "dabase.dev."

  # Redirect records for old domains
  Route53RecordSetRedirectDabaseDev:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabaseOld
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseDevRedirectDomainName

  Route53RecordSetRedirectAboutDabaseDev:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabaseOld
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "about.dabase.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionAboutDabaseDevRedirectDomainName


