Resources:
  Route53HostedZoneDabase:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "smartquery.dev."

  Route53RecordSetDabaseUi:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "smartquery.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseUiDomainName

  Route53RecordSetDabaseAboout:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "about.smartquery.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseAboutDomainName

  Route53RecordSetDabaseCloud:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "cloud.smartquery.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z215JYRZR1TBD5"  # Fixed hosted zone ID for Elastic Beanstalk in eu-central-1
        DNSName: !ImportValue DabaseCloudElasticBeanstalkEndpointUrl

  Route53RecordSetBastion:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "bastion.smartquery.dev."
      Type: "A"
      TTL: "300"
      ResourceRecords:
        - !ImportValue DabaseCloudBastionPublicIP

  Route53RecordSetSesDkim1:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: !ImportValue DkimDNSTokenName1
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue1

  Route53RecordSetSesDkim2:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: !ImportValue DkimDNSTokenName2
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue2

  Route53RecordSetSesDkim3:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: !ImportValue DkimDNSTokenName3
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - !ImportValue DkimDNSTokenValue3

  Route53RecordSetDmarc:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "_dmarc.smartquery.dev."
      Type: "TXT"
      TTL: "3600"
      ResourceRecords:
        - '"v=DMARC1; p=reject; rua=mailto:dmarc@smartquery.dev"'

  Route53RecordSetSpaceshipMx:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "smartquery.dev."
      Type: "MX"
      TTL: "3600"
      ResourceRecords:
        - "0 mx1.efwd.spaceship.net."
        - "0 mx2.efwd.spaceship.net."

  Route53RecordSetSpaceshipSpfAndStripeVerification:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "smartquery.dev."
      Type: "TXT"
      TTL: "3600"
      ResourceRecords:
        - '"stripe-verification=b675f45f2d01cd1774e0f4278720e194cb3f270ee7f382b09baecaf7a405741c"'
        - '"stripe-verification=f8137c32c9086ff8c31fa71aa54425f4a8291f0a91cc1efac15b3cb7e890a029"'
        - '"v=spf1 include:spf.efwd.spaceship.net ~all"'

  Route53RecordSetStripeDkim1:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "s3rffjeocaxxfut6wdu44i7vehx2uj5j._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "s3rffjeocaxxfut6wdu44i7vehx2uj5j.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkim2:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "b4duab33kjqcufz5wdcm5rmmqxp7bp7t._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "b4duab33kjqcufz5wdcm5rmmqxp7bp7t.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkim3:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "dd3cgupkaeimjf65taelxznf2qgdq3n6._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "dd3cgupkaeimjf65taelxznf2qgdq3n6.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkim4:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "dtb25znqdfzorsexuowotxg3jk3vaxrr._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "dtb25znqdfzorsexuowotxg3jk3vaxrr.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkim5:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "bgt2j4ti4cnh7uufqzxylpkjn3nnrhf7._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "bgt2j4ti4cnh7uufqzxylpkjn3nnrhf7.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeDkim6:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "gsdw7senfn5tkd32jic4uvzmjdvd5zvz._domainkey.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "gsdw7senfn5tkd32jic4uvzmjdvd5zvz.dkim.custom-email-domain.stripe.com."

  Route53RecordSetStripeBounce:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "smartquery.dev."
      Name: "bounce.smartquery.dev."
      Type: "CNAME"
      TTL: "3600"
      ResourceRecords:
        - "custom-email-domain.stripe.com."

  # Old domain hosted zone for redirects
  Route53HostedZoneDabaseOld:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "dabase.dev."

  # Redirect records for old domains
  Route53RecordSetRedirectDabaseDev:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabaseOld
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseDevRedirectDomainName

  Route53RecordSetRedirectAboutDabaseDev:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabaseOld
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "about.dabase.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionAboutDabaseDevRedirectDomainName


