Resources:
  Route53HostedZoneDabase:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: "dabase.dev."

  Route53RecordSetEmail:
    Type: "AWS::Route53::RecordSet"
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "MX"
      TTL: "3600"
      ResourceRecords:
        - "1 SMTP.GOOGLE.COM"
        - "5 ALT1.ASPMX.L.GOOGLE.COM"
        - "5 ALT2.ASPMX.L.GOOGLE.COM"
        - "10 ALT3.ASPMX.L.GOOGLE.COM"
        - "10 ALT4.ASPMX.L.GOOGLE.COM"

  Route53RecordSetDabaseUi:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "dabase.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseUiDomainName

  Route53RecordSetDabaseAboout:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "about.dabase.dev."
      Type: "A"
      AliasTarget:
        # This is the CloudFront hosted zone ID, which is fixed for CloudFront
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !ImportValue CloudFrontDistributionDabaseAboutDomainName

  Route53RecordSetDabaseCloud:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "cloud.dabase.dev."
      Type: "A"
      AliasTarget:
        HostedZoneId: "Z215JYRZR1TBD5"  # Fixed hosted zone ID for Elastic Beanstalk in eu-central-1
        DNSName: !ImportValue DabaseCloudElasticBeanstalkEndpointUrl

  Route53RecordSetBastion:
    Type: AWS::Route53::RecordSet
    DependsOn: Route53HostedZoneDabase
    Properties:
      HostedZoneName: "dabase.dev."
      Name: "bastion.dabase.dev."
      Type: "A"
      TTL: "300"
      ResourceRecords:
        - !ImportValue DabaseCloudBastionPublicIP
      