Resources:
  RUMAppMonitor:
    Type: AWS::RUM::AppMonitor
    Properties:
      AppMonitorConfiguration: 
          AllowCookies: True
          EnableXRay: True
          GuestRoleArn: !ImportValue CognitoIAMRoleArn
          IdentityPoolId: !ImportValue CognitoIdentityPoolId
      DeobfuscationConfiguration:
        JavaScriptSourceMaps:
          Status: ENABLED
          S3Uri: s3://smartquery-ui/sourcemaps
      Domain: smartquery.dev
      Name: smartquery
