Resources:
  S3BucketCodePipeline:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "smartquery-codepipeline"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketLink:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "smartquery-link"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketPolicyLink:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Bucket: !Ref S3BucketLink
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "arn:aws:s3:::smartquery-link/*"
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Sid: "PublicReadGetObject"

  S3BucketCloudSource:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "smartquery-cloud-source"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter24Hours
            Status: Enabled
            ExpirationInDays: 1

  S3BucketUi:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "smartquery-ui"
      CorsConfiguration:
        CorsRules:
          - MaxAge: 3000
            AllowedMethods:
              - "GET"
              - "POST"
              - "PUT"
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketPolicyUi:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Bucket: !Ref S3BucketUi
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "arn:aws:s3:::smartquery-ui/*"
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Sid: "PublicReadGetObject"
          - Resource: 
              - "arn:aws:s3:::smartquery-ui"
              - "arn:aws:s3:::smartquery-ui/sourcemaps/*"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
            Effect: "Allow"
            Principal:
              Service: "rum.amazonaws.com"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
                aws:SourceArn: !Sub "arn:${AWS::Partition}:rum:${AWS::Region}:${AWS::AccountId}:appmonitor/smartquery"
            Sid: "RUMSourceMapAccess"

  S3BucketAbout:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "smartquery-about"
      CorsConfiguration:
        CorsRules:
          - MaxAge: 3000
            AllowedMethods:
              - "GET"
              - "POST"
              - "PUT"
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketPolicyAbout:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Bucket: !Ref S3BucketAbout
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "arn:aws:s3:::smartquery-about/*"
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Sid: "PublicReadGetObject"

Outputs:
  S3BucketCodePipeline:
    Value: !Ref S3BucketCodePipeline
    Export:
      Name: "S3BucketCodePipeline"
  S3BucketUi:
    Value: !Ref S3BucketUi
    Export:
      Name: "S3BucketUi"
  S3BucketAbout:
    Value: !Ref S3BucketAbout
    Export:
      Name: "S3BucketAbout"
