Resources:
  S3BucketCodePipeline:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "dabase-codepipeline"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketDabaseLink:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "dabase-link"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketPolicyDabaseLink:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Bucket: !Ref S3BucketDabaseLink
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "arn:aws:s3:::dabase-link/*"
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Sid: "PublicReadGetObject"

  S3BucketDabaseUi:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "dabase-ui"
      CorsConfiguration:
        CorsRules:
          - MaxAge: 3000
            AllowedMethods:
              - "GET"
              - "POST"
              - "PUT"
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketPolicyDabaseUi:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Bucket: !Ref S3BucketDabaseUi
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "arn:aws:s3:::dabase-ui/*"
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Sid: "PublicReadGetObject"

  S3BucketDabaseAbout:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        BlockPublicAcls: false
      BucketName: "dabase-about"
      CorsConfiguration:
        CorsRules:
          - MaxAge: 3000
            AllowedMethods:
              - "GET"
              - "POST"
              - "PUT"
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

  S3BucketPolicyDabaseAbout:
    Type: "AWS::S3::BucketPolicy"
    DeletionPolicy: "Delete"
    UpdateReplacePolicy: "Delete"
    Properties:
      Bucket: !Ref S3BucketDabaseAbout
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: "arn:aws:s3:::dabase-about/*"
            Action: "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Sid: "PublicReadGetObject"

Outputs:
  S3BucketCodePipeline:
    Value: !Ref S3BucketCodePipeline
    Export:
      Name: "S3BucketCodePipeline"
  S3BucketDabaseUi:
    Value: !Ref S3BucketDabaseUi
    Export:
      Name: "S3BucketDabaseUi"
  S3BucketDabaseAbout:
    Value: !Ref S3BucketDabaseAbout
    Export:
      Name: "S3BucketDabaseAbout"
