AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Secrets Manager - Dabase Cloud'

Resources:
  DabaseCloudDbSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-db-secret'
      GenerateSecretString:
        PasswordLength: 32
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        ExcludeCharacters: '"@/'

  DabaseCloudGoogleAiApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-google-ai-api-key'

  DabaseCloudJwtSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-jwt-secret'
      GenerateSecretString:
        PasswordLength: 32

Outputs:
  DabaseCloudDbSecretArn:
    Value: !Ref DabaseCloudDbSecret
    Export:
      Name: DabaseCloudDbSecretArn

  DabaseCloudJwtSecretArn:
    Value: !Ref DabaseCloudJwtSecret
    Export:
      Name: DabaseCloudJwtSecretArn

  DabaseCloudJwtSecretName:
    Value: !Ref DabaseCloudJwtSecret
    Export:
      Name: DabaseCloudJwtSecretName
