AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Secrets Manager -  Cloud'

Resources:
  CloudDbSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-db-secret'
      GenerateSecretString:
        PasswordLength: 32
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        ExcludeCharacters: '"@/'

  CloudGoogleAiApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-google-ai-api-key'

  CloudJwtSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-jwt-secret'
      GenerateSecretString:
        PasswordLength: 32

  CloudStripeApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-stripe-api-key'

  CloudStripeWebhookSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-stripe-webhook-secret'

Outputs:
  CloudDbSecretArn:
    Value: !Ref CloudDbSecret
    Export:
      Name: CloudDbSecretArn

  CloudGoogleAiApiKeyArn:
    Value: !Ref CloudGoogleAiApiKey
    Export:
      Name: CloudGoogleAiApiKeyArn

  CloudJwtSecretArn:
    Value: !Ref CloudJwtSecret
    Export:
      Name: CloudJwtSecretArn

  CloudStripeApiKeyArn:
    Value: !Ref CloudStripeApiKey
    Export:
      Name: CloudStripeApiKeyArn

  CloudStripeWebhookSecretArn:
    Value: !Ref CloudStripeWebhookSecret
    Export:
      Name: CloudStripeWebhookSecretArn
