AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Secrets Manager - Dabase Cloud'

Resources:
  DabaseCloudDbSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-db-secret'
      GenerateSecretString:
        PasswordLength: 32
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        ExcludeCharacters: '"@/'

  DabaseCloudGoogleAiApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-google-ai-api-key'

  DabaseCloudJwtSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-jwt-secret'
      GenerateSecretString:
        PasswordLength: 32

  DabaseCloudStripeApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-stripe-api-key'

  DabaseCloudStripeWebhookSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-stripe-webhook-secret'

Outputs:
  DabaseCloudDbSecretArn:
    Value: !Ref DabaseCloudDbSecret
    Export:
      Name: DabaseCloudDbSecretArn

  DabaseCloudGoogleAiApiKeyArn:
    Value: !Ref DabaseCloudGoogleAiApiKey
    Export:
      Name: DabaseCloudGoogleAiApiKeyArn

  DabaseCloudJwtSecretArn:
    Value: !Ref DabaseCloudJwtSecret
    Export:
      Name: DabaseCloudJwtSecretArn

  DabaseCloudStripeApiKeyArn:
    Value: !Ref DabaseCloudStripeApiKey
    Export:
      Name: DabaseCloudStripeApiKeyArn

  DabaseCloudStripeWebhookSecretArn:
    Value: !Ref DabaseCloudStripeWebhookSecret
    Export:
      Name: DabaseCloudStripeWebhookSecretArn
