AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Secrets Manager - Smartquery Cloud'

Resources:
  SmartqueryCloudDbSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-db-secret'
      GenerateSecretString:
        PasswordLength: 32
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: 'password'
        ExcludeCharacters: '"@/'

  SmartqueryCloudGoogleAiApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-google-ai-api-key'

  SmartqueryCloudJwtSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-jwt-secret'
      GenerateSecretString:
        PasswordLength: 32

  SmartqueryCloudStripeApiKey:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-stripe-api-key'

  SmartqueryCloudStripeWebhookSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'smartquery-cloud-stripe-webhook-secret'

Outputs:
  SmartqueryCloudDbSecretArn:
    Value: !Ref SmartqueryCloudDbSecret
    Export:
      Name: SmartqueryCloudDbSecretArn

  SmartqueryCloudGoogleAiApiKeyArn:
    Value: !Ref SmartqueryCloudGoogleAiApiKey
    Export:
      Name: SmartqueryCloudGoogleAiApiKeyArn

  SmartqueryCloudJwtSecretArn:
    Value: !Ref SmartqueryCloudJwtSecret
    Export:
      Name: SmartqueryCloudJwtSecretArn

  SmartqueryCloudStripeApiKeyArn:
    Value: !Ref SmartqueryCloudStripeApiKey
    Export:
      Name: SmartqueryCloudStripeApiKeyArn

  SmartqueryCloudStripeWebhookSecretArn:
    Value: !Ref SmartqueryCloudStripeWebhookSecret
    Export:
      Name: SmartqueryCloudStripeWebhookSecretArn
