AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Secrets Manager - Dabase Cloud'

Resources:
  DabaseCloudJwtSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: 'dabase-cloud-jwt-secret'
      GenerateSecretString:
        PasswordLength: 32

Outputs:
  DabaseCloudJwtSecretArn:
    Value: !Ref DabaseCloudJwtSecret
    Export:
      Name: DabaseCloudJwtSecretArn

  DabaseCloudJwtSecretName:
    Value: !Ref DabaseCloudJwtSecret
    Export:
      Name: DabaseCloudJwtSecretName
