services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresql_db
    network_mode: 'host'
    ports:
      - '${VITE_POSTGRESQL_PORT}:5432'
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: password
    network_mode: 'host'
    ports:
      - '${VITE_MYSQL_PORT}:3306'
