services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - '${VITE_POSTGRESQL_PORT}:5432'
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '${VITE_MYSQL_PORT}:3306'
