import type { Connection } from '~/shared/types';

export const initialConnections = [
  {
    credentialStorage: 'localStorage',
    database: 'postgresql_db',
    engine: 'postgresql',
    host: 'localhost',
    id: '0',
    name: 'PostgreSQL',
    password: 'password',
    port: 5433,
    ssh: null,
    user: 'postgres',
  },
  {
    credentialStorage: 'localStorage',
    database: 'mysql_db',
    engine: 'mysql',
    host: 'localhost',
    id: '1',
    name: 'MySQL',
    password: 'password',
    port: 3307,
    ssh: null,
    user: 'root',
  },
  {
    credentialStorage: 'localStorage',
    database: 'mathewson_metals_development',
    engine: 'postgresql',
    host: 'localhost',
    id: '2',
    name: 'Mathewson Metals',
    password: 'password',
    port: 5432,
    ssh: null,
    user: 'postgres',
  },
  {
    credentialStorage: 'alwaysAsk',
    database: 'cosuno_development',
    engine: 'mysql',
    host: 'localhost',
    id: '3',
    name: 'Cosuno Development',
    password: null,
    port: 3306,
    ssh: null,
    user: 'root',
  },
] satisfies Connection[];
