export const dataTypes = [
  'bigint',
  'boolean',
  'char',
  'character varying',
  'datetime',
  'decimal',
  'enum',
  'int',
  'integer',
  'json',
  'numeric',
  'time with time zone',
  'time without time zone',
  'time',
  'timestamp with time zone',
  'timestamp without time zone',
  'timestamp',
  'tinyint',
  'user-defined',
  'varchar',
] as const;
