export const dataTypes = [
  'bigint',
  'boolean',
  'char',
  'character varying',
  'date',
  'datetime',
  'decimal',
  'double precision',
  'enum',
  'int',
  'integer',
  'json',
  'numeric',
  'real',
  'time with time zone',
  'time without time zone',
  'time',
  'timestamp with time zone',
  'timestamp without time zone',
  'timestamp',
  'tinyint',
  'user-defined',
  'varchar',
] as const;
