export const PLUS_MAX_AI_CHAT_INPUT_TOKENS = 1_500_000;
export const PLUS_MAX_AI_CHAT_OUTPUT_TOKENS = 62_500;
export const PLUS_MAX_AI_INLINE_COMPLETION_INPUT_TOKENS = 20_000_000;
export const PLUS_MAX_AI_INLINE_COMPLETION_OUTPUT_TOKENS = 2_000_000;
export const PLUS_MAX_CONCURRENT_CONNECTIONS = 3;
export const PLUS_MAX_CONCURRENT_QUERY_STATEMENTS = 5;
export const PLUS_MAX_QUERY_DURATION_SECONDS = 50_000;
export const PLUS_MAX_QUERY_RESPONSE_BYTES = 2 * 1024 * 1024 * 1024; // 2GB
